INSERT INTO currencies (code, name, scale, periodicity, sort_order, is_active, source)
VALUES
  ('BYN', 'Белорусский рубль', 1, 0, 1, true, 'system'),
  ('USD', 'Доллар США', 1, 0, 2, true, 'nbrb'),
  ('EUR', 'Евро', 1, 0, 3, true, 'nbrb'),
  ('RUB', 'Российских рублей', 100, 0, 4, true, 'nbrb'),
  ('AUD', 'Австралийский доллар', 1, 0, 100, true, 'nbrb'),
  ('AMD', 'Армянских драмов', 1000, 0, 110, true, 'nbrb'),
  ('BRL', 'Бразильских реалов', 10, 0, 120, true, 'nbrb'),
  ('UAH', 'Гривен', 100, 0, 130, true, 'nbrb'),
  ('DKK', 'Датских крон', 10, 0, 140, true, 'nbrb'),
  ('AED', 'Дирхамов ОАЭ', 10, 0, 150, true, 'nbrb'),
  ('VND', 'Донгов', 100000, 0, 160, true, 'nbrb'),
  ('PLN', 'Злотых', 10, 0, 170, true, 'nbrb'),
  ('JPY', 'Иен', 100, 0, 180, true, 'nbrb'),
  ('INR', 'Индийских рупий', 100, 0, 190, true, 'nbrb'),
  ('IRR', 'Иранских риалов', 100000, 0, 200, true, 'nbrb'),
  ('ISK', 'Исландских крон', 100, 0, 210, true, 'nbrb'),
  ('CAD', 'Канадский доллар', 1, 0, 220, true, 'nbrb'),
  ('CNY', 'Китайских юаней', 10, 0, 230, true, 'nbrb'),
  ('KWD', 'Кувейтский динар', 1, 0, 240, true, 'nbrb'),
  ('MDL', 'Молдавских леев', 10, 0, 250, true, 'nbrb'),
  ('NZD', 'Новозеландский доллар', 1, 0, 260, true, 'nbrb'),
  ('NOK', 'Норвежских крон', 10, 0, 270, true, 'nbrb'),
  ('SGD', 'Сингапурский доллар', 1, 0, 290, true, 'nbrb'),
  ('KGS', 'Сомов', 100, 0, 300, true, 'nbrb'),
  ('KZT', 'Тенге', 1000, 0, 310, true, 'nbrb'),
  ('TRY', 'Турецких лир', 10, 0, 320, true, 'nbrb'),
  ('GBP', 'Фунт стерлингов', 1, 0, 330, true, 'nbrb'),
  ('CZK', 'Чешских крон', 100, 0, 340, true, 'nbrb'),
  ('SEK', 'Шведских крон', 10, 0, 350, true, 'nbrb'),
  ('CHF', 'Швейцарский франк', 1, 0, 360, true, 'nbrb')
ON CONFLICT (code) DO UPDATE
SET
  name = EXCLUDED.name,
  scale = EXCLUDED.scale,
  periodicity = EXCLUDED.periodicity,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active,
  source = EXCLUDED.source,
  updated_at = now();
